**How create a null values in a data**

In [7]:
import numpy as np
import pandas as pd

In [8]:
d={'Names':['Ramesh','Suresh',None,'Mahesh'],
    'Age':[None,22,24,25],
   'City':['Hyd','Blr','Pune',None]}
df1=pd.DataFrame(d)
df1

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0  None

In [9]:
d={'Names':['Ramesh','Suresh',None,'Mahesh'],
    'Age':[None,22,24,25],
   'City':['Hyd','Blr','Pune',None]}
df2=pd.DataFrame(d)
df2.to_csv('data2.csv',index=False)
df2

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0  None

In [ ]:
- Categorical data use none
-

In [10]:
df1

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0  None

In [ ]:
df1
df1.values
df1.dtypes
df1.isnull()
df1.isnull().sum()

In [11]:
df1

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0  None

In [17]:
df1.values

array([['Ramesh', nan, 'Hyd'],
       ['Suresh', 22.0, 'Blr'],
       [None, 24.0, 'Pune'],
       ['Mahesh', 25.0, None]], dtype=object)

In [18]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

In [12]:
df1.isnull()

   Names    Age   City
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True

In [13]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**Fill the values**

In [22]:
#Random fill
df1.fillna(30)

    Names   Age  City
0  Ramesh  30.0   Hyd
1  Suresh  22.0   Blr
2      30  24.0  Pune
3  Mahesh  25.0    30

In [14]:
# select one column and will with value
df1['City'].fillna('Delhi')

0      Hyd
1      Blr
2     Pune
3    Delhi
Name: City, dtype: object

In [ ]:
df1.fillna(30)
df['City'].fillna('Delhi')

In [15]:
# pad,bfill,ffill,backfill
#axis=0 axis=1
df1.fillna(method='pad')
df1

C:\Users\lavan\AppData\Local\Temp\ipykernel_21620\301331543.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad')

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0  None

In [20]:
df1.fillna(method='pad',axis=1)

C:\Users\lavan\AppData\Local\Temp\ipykernel_21620\1258234312.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad',axis=1)

    Names     Age  City
0  Ramesh  Ramesh   Hyd
1  Suresh    22.0   Blr
2    None    24.0  Pune
3  Mahesh    25.0  25.0

In [17]:
df1.fillna(method='bfill')

C:\Users\lavan\AppData\Local\Temp\ipykernel_21620\2259200643.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill')

    Names   Age  City
0  Ramesh  22.0   Hyd
1  Suresh  22.0   Blr
2  Mahesh  24.0  Pune
3  Mahesh  25.0  None

In [32]:
df1.fillna(method='bfill',axis=1)

C:\Users\lavan\AppData\Local\Temp\ipykernel_14388\2900121331.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill',axis=1)

    Names   Age  City
0  Ramesh   Hyd   Hyd
1  Suresh  22.0   Blr
2    24.0  24.0  Pune
3  Mahesh  25.0  None

- mean
- median
- mode

In [33]:
age_mean=df1['Age'].mean()
df1['Age'].fillna(age_mean)

0    23.666667
1    22.000000
2    24.000000
3    25.000000
Name: Age, dtype: float64

In [ ]:
# there is no particular rule how to fille the missing the values
# it is completely based on situation

In [36]:
Gender=['Male','Female',None]
d1=pd.DataFrame(Gender,columns=['Gender'])

In [37]:
d1 # i want to handover this data to my students with not encode

   Gender
0    Male
1  Female
2    None

In [38]:
d={'Female':0,'Male':1}
d1['Gender']=d1['Gender'].map(d)
d1

   Gender
0     1.0
1     0.0
2     NaN

In [39]:
#  the students think that i want to fill a missing
# data is numerical: mean
(1+0)/2

0.5

**Situation:2**

In [ ]:
# ML algorithm
# churn ; stay or not stay
churn=['stay','not_stay',None]
churn=[0,1,None]
churn=[0,1,0.5]

**situation:3**

In [41]:
# no of days
[20,25,np.nan,31]
(20+25+31)/3

25.333333333333332

**situation:4**

In [ ]:
course=['DS','AI','DS','Devops','AI','Devops','AI']
fee=[30000,2700,30000,22000,3000,22000,np.nan]
pd.DataFrame(course,fee)

**KNNImputer**

- KNN : K-nearest neighbours
- where K is a number
- instead of taking avg of all the values data
   - first will find the neighbours who are close with missing data
   - by using Euclidian distance calculation will identify the neighbour rows
   - suppose k=2 will identify the two closest rows
   - those closest rows values will take it,will calculate the mean
   - finally will fill with the mean

In [43]:
salary=[50000,np.nan,70000,90000]
age=[25,28,30,40]
df=pd.DataFrame(zip(salary,age),columns=['Salary','Age'])
df

    Salary  Age
0  50000.0   25
1      NaN   28
2  70000.0   30
3  90000.0   40

- sklearn
  - impute
  - KNNImputer

In [45]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=2)
pd.DataFrame(imputer.fit_transform(df))

         0     1
0  50000.0  25.0
1  60000.0  28.0
2  70000.0  30.0
3  90000.0  40.0